### PR TITLE
Apidocs update (Alice Jaques)

### PR DESCRIPTION
**Pull request by iglesu**

### CODE REVIEW

**Comment by rnikutta** [comment]
Hi @iglesu I just pip installed (from pypi) the latest astro-datalab. It downloaded and installed fine. The version reported though is v2.23.0 (but should be v2.23.1 I think?) Did we miss a version-string update somewhere maybe? Or should the CI job update that? Thanks.

**Comment by rnikutta** [comment]
(by "version reported" I mean when you do "datalab version")

**Comment by iglesu** [comment]
do 
pip uninstall astro-datalab

followed by

pip install astro-datalab

that should pick 2.23.1

also make sure you are not in the datalab repo as it might pick up the local version, perhaps one git pull behind

**Comment by rnikutta** [comment]
Hi @iglesu , I did yesterday this

`pip install --ignore-installed --no-cache-dir astro-datalab`

which is the incantation we have in our README file. And I was not in the datalab repo dir.

Could it have picked up the wrong version because of my recent (local) experiment installing this from sources? (which ended up in `$HOME/.local/bin/` rather than in any of my conda envs)

**Comment by rnikutta** [comment]
Ok fixed it. I needed to reload my .bashrc file, because it was still picking up the old $PATH before. v2.23.1 is now installed, and picked correctly. Thank you!

**Comment by iglesu** [comment]
Robert, Since that command works in my environment and in other linux machines, I'm inclined to think it is environment related, for instance make sure your PYTHONPATH is not set. 


This little program might shed some light on where are you sourcing your module from:

import inspect
import importlib

# Import the module dynamically
module_name = 'dl'
module = importlib.import_module(module_name)

# Use inspect to find the source file of the module
module_file = inspect.getfile(module)

print(f"Module {module_name} is located at: {module_file}")

# Optionally, read the content of the module to find __version__
with open(module_file, 'r') as file:
    for line in file:
        if '__version__' in line:
            print(line.strip())


also did you try the commands I sent you yesterday. I assume they didn't work, correct?

Thanks,

Igor

**Pull request merged**
