### PR TITLE
Vospace 20210428 final

### PR DESCRIPTION
**Pull request by iglesu**
This pull request is part of the VOSpace performance improvements, with changes to vospace, storagemanager and datalab/storeClient.py

The "ls" methods do a quick check to see if the string passed in is an
auth token.
E.g.

testuser.3666.3666.$1$PKCFmMzy$OPpZg/ThBmZe/V8LVPvpi/%

Originally it did so by counting the number of dots (.) in
the string. So a file name such as:

0000m091.1.mod.fits

would also be considered a token and the "ls" command returned with a:
"Not Found"

I added the "is_auth_token" method, which does a thorough regex for what
we expect an auth token to be, making sure that especial cases, such as
anonymous and dldemo tokens are also matched,
and replace the dot counting in the "ls" methods for the "is_auth_token"
check.

### CODE REVIEW

**Review by mjfitzpatrick — CHANGES_REQUESTED** [review]
The is_auth_token() is a much better implementation for determining a token lexically, it should be incorporated in the authmanager validation as well.  However, the 'optval' argument is used in more than just the ls() client method, so this change should be applied to all client methods.  Also, the "master" copy of the client codes is in the manager repos, they are copied to the 'datalab' package with each new release -- please issue a PR against the storagemanager/storeClient.py

**Comment by iglesu** [comment]
Hi Mike, I'd like to address this unfinished business in the python3 managers branches. I'd like to add the is_auth_token function but I'm not sure where is best. I'm thinking of two places: the authClient and the dl/Util.py. The authClient will sound logical but is_auth_token is not an authmanager api, just a utility method that checks the string format, so in that sense the Util.py might make more sense. Do you have any preferences? thanks!

**Comment by mjfitzpatrick** [comment]
Since it could be used by all clients/managers, it should be in the Util.py
to avoid there being out-of-sync duplicates.

**Comment by mjfitzpatrick** [comment]
@iglesu Is this PR still valid and in needing of a merge before the updated gp08?

**Comment by iglesu** [comment]
This pull request was superseded by PR #55

**Pull request closed without merging**
