### PR TITLE
Change async to async_, update examples, uniform output

### PR DESCRIPTION
**Pull request by jacquesalice**
Same as [PR#97 in the querymanager](https://github.com/astro-datalab/querymanager/pull/97) repo

### CODE REVIEW

**Review by chaduhduh — APPROVED** [review]
Looks fine to me @jacquesalice! All of the documentation updates appear to be present but I will defer to @iglesu for the other code changes.

**Comment by rnikutta** [comment]
@jacquesalice the clients are currently developed inside the managers repos. We then copy the clients .py files over here to update the datalab package. So can you please close this PR, and apply the changes in the queryClient.py file in the querymanager repo instead? Thanks!

**Comment by jacquesalice** [comment]
@rnikutta oh I did that already in the querymanager here: https://github.com/astro-datalab/querymanager/pull/97 , then @iglesu and @chaduhduh said to make a PR with the same updated `queryClient.py` file in this repo....

**Comment by rnikutta** [comment]
Oh, apologies! I did check for PRs in querymanager but didn't check for already merged ones! Sorry!

**Comment by iglesu** [comment]
Sorry, but there are to much entangle code from querymanager commits related to PR #67 and other commits that it's a lot easier if we move this to PR #67. Depending on how the test on #67 goes will close this PR.

**Pull request closed without merging**
